[binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"
